### ISSUE TITLE
Can't build project, for lack of Deconstruct method on KeyValuePairs

### ISSUE THREAD

**Issue by natronium** [dpinela/DeathsDoor.ItemChanger#2]
After cloning the repository, copying the DLLs from the Death's Door `Managed` folder and the bepinex dlls from the `BepInEx/Core` folder, and publicizing `Assembly-CSharp.dll`, I can't seem to compile the mod. All attempts at building fail with:

```
C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChangerPlugin.cs(27,75): error CS1061: 'KeyValuePair<string, string>' does not contain a definition for 'Deconstruct' and no accessible extension method 'Deconstruct' accepting a first argument of type 'KeyValuePair<string, string>' could be found (are you missing a using directive or an assembly reference?) [C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChanger.csproj]
C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChangerPlugin.cs(27,58): error CS8129: No suitable 'Deconstruct' instance or extension method was found for type 'KeyValuePair<string, string>', with 2 out parameters and a void return type. [C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChanger.csproj]
C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChangerPlugin.cs(27,31): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'locationName'. [C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChanger.csproj]
C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChangerPlugin.cs(27,45): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'itemName'. [C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChanger.csproj]
C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChangerPlugin.cs(46,71): error CS1061: 'KeyValuePair<string, Item>' does not contain a definition for 'Deconstruct' and no accessible extension method 'Deconstruct' accepting a first argument of type 'KeyValuePair<string, Item>' could be found (are you missing a using directive or an assembly reference?) [C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChanger.csproj]
C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChangerPlugin.cs(46,54): error CS8129: No suitable 'Deconstruct' instance or extension method was found for type 'KeyValuePair<string, Item>', with 2 out parameters and a void return type. [C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChanger.csproj]
C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChangerPlugin.cs(46,31): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'locationName'. [C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChanger.csproj]
C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChangerPlugin.cs(46,45): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'item'. [C:\Users\na\source\repos\DeathsDoor.ItemChanger\ItemChanger\ItemChanger.csproj]
```

Some googling turned up [this blog post](https://www.interact-sw.co.uk/iangblog/2018/04/12/deconstruct-keyvaluepair) and [these library docs](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair-2.deconstruct?view=net-9.0#applies-to) which suggest that .NET 4.7.2 (the TargetFramework in the csproj) doesn't implement `Deconstruct` for `KeyValuePair`s.

How am I supposed to build this mod from source?

**Comment by dpinela** [comment]
Which compiler are you using? I currently have .NET 8.0.411, which builds as expected.

**Comment by natronium** [comment]
`dotnet --version` was reporting .NET 8.0.302, but trying to run `dotnet build` using .NET 8.0.411 (via global.json) fails the same way, as does trying to build using the 9.0.302 release that Visual Studio installed for me with its latest update. I've also tried building the project directly via VSCode's C# extension (Solution Explorer -> Right click the project -> Build) and Visual Studio Community 2022 (same ui flow as VSCode) with the same build error. All on windows.

As far as i can tell, this is a target framework issue? Since the TargetFramwork specified in the csproj is `net472` my assumption is that the compiler can't rely on `KeyValuePair` having a `Deconstruct` implementation, and fails the build as a result.

What confuses me the most tbh, is that clearly there's *some* configuration that builds things just fine, and results in a dll with a TargetFramework of 4.7.2 *and* references to `KeyValuePair.Deconstruct`, (I checked with DnSpy!) but my extremely non-expert impression suggests that that shouldn't be possible.

**Comment by dpinela** [comment]
The only difference I can think of is that I am building on macOS - otherwise I am as confused as you.
